// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmbxogegsfybrswvvrdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttYnhvZ2Vnc2Z5YnJzd3Z2cmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzAyODgsImV4cCI6MjA1OTg0NjI4OH0.uyyUGbeGzAawvsJW2yKIqcUevS2kqrxyzHABN8UIKVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);